name: Test Notebooks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run every week on Monday at 10:00 UTC
    - cron: '0 10 * * 1'

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false  # Don't cancel other jobs if one fails
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libfftw3-dev \
          liblapack-dev \
          libblas-dev \
          gfortran
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install additional testing dependencies
      run: |
        pip install nbconvert pytest timeout-decorator
        
    - name: Test all notebooks in notebook/ directory
      run: |
        python test_notebooks.py --directory notebook
        
    - name: Test all notebooks in book-version/ directory  
      run: |
        python test_notebooks.py --directory book-version
        
    - name: Upload test artifacts on failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: notebook-test-failures-py${{ matrix.python-version }}
        path: |
          test-failures/
          *.log
        retention-days: 7
